### ISSUE TITLE
Pourquoi "project_id" dans les users ?

### ISSUE THREAD

**Issue by korasaccharin** [arnaudlevy/mmiworkshop#3]
Est-ce que les étudiants n'ont qu'un seul projet ? Les étudiants n'ont qu'un seul projet par année, mais participent-ils au workshop deux ans d'affilée ? Auquel cas, transformer cette colonne en un has and belongs to many ?

**Comment by arnaudlevy** [comment]
Les étudiants n'ont qu'un projet, et on verra l'an prochain si ça fonctionne ou pas !
